version: '3'
services:
  vue:
    build:
      context: ./frontend
    ports:
      - '4173:4173'
    restart: unless-stopped

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    #ports:
    #  - "5432:5432"
    restart: "always"

  backend:
    build:
      context: ./backend
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: pgdb
    depends_on:
      - pgdb
    ports:
      - '3000:3000'
    restart: always

volumes:
  pgdbdata: null
